# Generated by Django 4.2.6 on 2023-10-19 08:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_bekamodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(max_length=100)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=155)),
            ],
        ),
    ]
