# Generated by Django 4.2.6 on 2023-10-19 10:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_clientmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='equipe')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='equipe')),
                ('description', ckeditor.fields.RichTextField(max_length=100)),
            ],
        ),
    ]
