# Generated by Django 4.2.6 on 2023-10-22 01:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_equipemodel_projetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
