# Generated by Django 4.2.6 on 2023-10-10 14:06

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('contenu', ckeditor.fields.RichTextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('est_publie', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField(default=0, help_text="Nombre de fois où l'article a été mis en avant ou partagé.")),
                ('views', models.PositiveIntegerField(default=0, help_text="Nombre de vues de l'article.")),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
    ]
