# Generated by Django 4.2.6 on 2023-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicesmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='category',
            field=models.CharField(max_length=155),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
