# Generated by Django 4.2.6 on 2023-10-19 10:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicesmodel_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('category', models.CharField(max_length=155)),
            ],
        ),
    ]
