# Generated by Django 4.2.6 on 2023-10-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_projetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetmodel',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
