# Generated by Django 4.2.6 on 2023-10-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('ALTERNANCE', 'ALTERNANCE')], max_length=100, verbose_name='Type de contrat'),
        ),
    ]
