# Generated by Django 4.2.6 on 2023-10-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriere', '0002_alter_offreemploi_type_contrat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soumission',
        ),
    ]
