# Generated by Django 4.2.6 on 2023-10-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriere', '0003_delete_soumission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreemploi',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='responsabilites',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='salaire',
        ),
    ]
