# Generated by Django 4.2.6 on 2023-10-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_offre_candidate_poste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemoignagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('title_temoignages', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
